version: '3.4'

services:

  backend-api:
    build: 
      context: src/backend
    # restart: always
    container_name: API_Backend
    environment:
      - Postgres__ConnectionString=User ID={user-id};Password={password};Server={connection-string};Port=5432;Database={database-name};Integrated Security=true;Pooling=true;
      - Authentication__ExpiresInMinutes=480
      - Authentication__SecretKey={auth-secret}
      - Authentication__Issuer={issuer-url}
      - Logging__LogLevel__Default=Warning
      - ASPNETCORE_URLS=http://*:5000
      - AllowedHosts=*
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5000:5000"
    networks:
      - machinekind-network

networks:
  machinekind-network:
    driver: bridge